### ISSUE TITLE
dummy profile pic in the user profile

### ISSUE THREAD

**Issue by Pukarki0** [Hrikisschitrakar/EasyRide#10]
there should be 4 different  dummy profile pic in the bus driver , user,  station manager and admin profile
![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/621282c0-24a5-4060-83d9-c9f6b9b26211)

**Comment by Hrikisschitrakar** [comment]
Yes, all the users have gotten their profile dummy pics. Below is an example:
<img width="241" alt="Screenshot 2024-05-18 at 00 56 43" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119427558/acc830c4-670f-46d3-b1cb-b588fb983f18">
