### ISSUE TITLE
signup button not needed in admin, station manager and bus driver login page.

### ISSUE THREAD

**Issue by Pukarki0** [Hrikisschitrakar/EasyRide#11]
signup button in admin, station manager and bus driver login page(which is not needed in their login) please remove it
  
![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/602f2564-ce71-4121-93d5-d5605cd066b7)
![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/2a12a94a-42ad-4a35-8e19-49b12f0af6bd)
![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/b743cc15-1d06-4740-8141-ef79f5b374bc)

**Comment by Hrikisschitrakar** [comment]
All there interfaces has been updated and only customers now have the option to sign in to the system. 
<img width="326" alt="Screenshot 2024-05-18 at 01 03 14" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119427558/2920a4d4-b2d3-485d-b172-fa1f99f2d5e7">
<img width="322" alt="Screenshot 2024-05-18 at 01 03 06" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119427558/0df67a03-fde2-4a87-b028-b83bb0c1f902">
<img width="330" alt="Screenshot 2024-05-18 at 01 02 59" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119427558/b867871f-122c-4b8e-9f88-e41f68bd8387">
