### ISSUE TITLE
manage profile option in station manager navigation bar.

### ISSUE THREAD

**Issue by Pukarki0** [Hrikisschitrakar/EasyRide#13]
while clicking on update button and add route button manages profile option in navigation is shown in station manager account which should not be there 
![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/0edeee73-52b5-429f-9753-329161c47610)

**Comment by Pramdip** [comment]
I have updated and solve this issue of navigation bar of showing manage profile
![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119594157/6da887da-7b6b-491e-b1f7-29126d16a507)
![Uploading image.png…]()
