### ISSUE TITLE
password criteria not meet properly 

### ISSUE THREAD

**Issue by Pukarki0** [Hrikisschitrakar/EasyRide#16]
password can be created with any number of digits without uppercase and lower alphabets (minimum 4 digits needed with upper case and lowercase alphabets). 

![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/91b831eb-9179-4212-bc35-e49bb3f8df6e)

**Comment by Pramdip** [comment]
I have updated and solve this issue
![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119594157/8e4d218d-d579-4625-a69c-33e0d30b3336)
