### ISSUE TITLE
same bus driver is assigned to different bus .

### ISSUE THREAD

**Issue by Pukarki0** [Hrikisschitrakar/EasyRide#17]
same bus driver should not be able to assigned in different bus please fix this issue

![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/2e2cb2a4-4d9a-416f-a390-d1e1f99459e2)

**Comment by Pramdip** [comment]
we have solve the issue and updated the table of bus driver as username is bus driver is same the the popup shows up
![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119594157/a06068eb-48b0-4b78-a273-1d8b9263601f)
![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119594157/d08ad3f3-d206-4a32-9f74-4551e7edd1a1)
