### ISSUE TITLE
automatically filling of passenger name, email, and telephone in booking ticket form.

### ISSUE THREAD

**Issue by Pukarki0** [Hrikisschitrakar/EasyRide#27]
while booking ticket the selected ticket passenger name telephone and email is not filled automatically.
 passenger name , telephone, and email should be automatically filled from the user database.
![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/08e46566-da61-4df3-929a-84532b49c5e6)

**Comment by Hrikisschitrakar** [comment]
Now the user credentials are automatically filled in the box field. However, if the user wishes to change any of those fields, they can easily do it.
<img width="465" alt="Screenshot 2024-05-18 at 00 59 25" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119427558/09e0a178-8838-40ca-8566-6bacd4473383">
