### ISSUE TITLE
remove bus name and warning error form driverdashboard

### ISSUE THREAD

**Issue by Pukarki0** [Hrikisschitrakar/EasyRide#28]
there is  warning error in the driver dashboard page and also the bus name is shown in the middle please fix this

![unnamed](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/5969d0a7-a1d9-470d-9a1b-655a598a4440)

**Comment by Hrikisschitrakar** [comment]
The names of the buses where it was not needed has been removed.
<img width="1104" alt="Screenshot 2024-05-18 at 00 53 14" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119427558/4f5956de-a989-4eff-bdb2-32dbcb0ba9ca">
