### ISSUE TITLE
password-reset.php

### ISSUE THREAD

**Issue by Sambriddhi-Data** [Hrikisschitrakar/EasyRide#29]
![issue_Hrikiss](https://github.com/Hrikisschitrakar/EasyRide/assets/119392962/86e33fc7-e7cf-4bf4-ad84-78d70061421b)

After entering the email, it redirects to an empty page. Please give a proper redirection.

**Comment by Hrikisschitrakar** [comment]
The issue is solved
<img width="447" alt="Screenshot 2024-05-18 at 00 48 28" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119427558/2f92679a-0b1d-4dd9-ac94-f4cb00cd6ba0">
