### ISSUE TITLE
Feedback after clicking 'Forgot Password'

### ISSUE THREAD

**Issue by Sambriddhi-Data** [Hrikisschitrakar/EasyRide#5]
There is no feedback or redirection after clicking 'Forgot Password'. Could you please redirect it to a new page.

<img width="325" alt="sdjvgds" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119392962/11278e8e-67f2-4184-92ea-e13c42931d13">

**Comment by Hrikisschitrakar** [comment]
I have pushed html file, css file and PHP file needed for this bug.
<img width="1440" alt="Screenshot 2024-04-17 at 10 57 33" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119427558/968e8972-e578-432b-b0f0-400f5266fa29">
