### ISSUE TITLE
connect pages to database

### ISSUE THREAD

**Issue by Pukarki0** [Hrikisschitrakar/EasyRide#6]
the login page has not been connected to  the database do please make connection to database

**Comment by Hrikisschitrakar** [comment]
Connection.php has already been pushed into the repository.
<img width="1440" alt="Screenshot 2024-04-17 at 10 54 53" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119427558/84438ff1-ac17-4ff7-89d5-e08934f0d935">
