### ISSUE TITLE
Fix Signup button

### ISSUE THREAD

**Issue by Pukarki0** [Hrikisschitrakar/EasyRide#7]
there is no Signup button on the dashboard so, Please fix this issue
![unnamed](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/e858e221-5c8b-4050-abe1-5dfc1689c88e)

**Comment by Pramdip** [comment]
I have fixed this issue  and added formal button for signup registration 
![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119594157/8047f0aa-eb6f-420f-804f-724a7b6fc8d2)
