### ISSUE TITLE
All drivers can change the departure status of the bus of which they are not assigned. ( Driver could only be able to change the Departure Status of the bus they are assigned for)

### ISSUE THREAD

**Issue by Pukarki0** [Hrikisschitrakar/EasyRide#8]
( Driver could only be able to change the Departure Status of the bus they are assigned for)

![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/7730ce3a-e5d6-4546-9987-59f58e30b5af)

**Comment by Hrikisschitrakar** [comment]
Now the bus driver can let the users know when the bus departed and when the bus has arrived if the bus is assigned to them.
<img width="872" alt="Screenshot 2024-05-18 at 00 54 15" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119427558/7baa52da-ad4f-4015-b835-14e34d679f74">
