### ISSUE TITLE
Current departure status of the bus not shown in the table in customer dashboard.

### ISSUE THREAD

**Issue by Pukarki0** [Hrikisschitrakar/EasyRide#9]
current departure status should be shown in the customer dashboard. 

![image](https://github.com/Hrikisschitrakar/EasyRide/assets/119550097/c3b4b878-0fc1-4db7-abc5-1b62a3197cbb)

**Comment by Hrikisschitrakar** [comment]
now the user can know if the bus has departed or not and only book those buses which are yet to be departed.
<img width="1419" alt="Screenshot 2024-05-18 at 00 56 51" src="https://github.com/Hrikisschitrakar/EasyRide/assets/119427558/98b20295-66d8-4ad0-ba50-5fb6d7f67862">
